name: Basic Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run shellcheck on scripts
        run: |
          echo "${{ secrets.USERPWD }}" | sudo -S apt-get update
          echo "${{ secrets.USERPWD }}" | sudo -S apt-get install -y shellcheck
          find . -type f -name "*.sh" -exec shellcheck {} +