name: Deploy Proxmox VMs

on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: self-hosted
    env:
      TF_VAR_access_key: ${{ secrets.ACCESS_KEY }}
      TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

    steps:
      # Checkout the github user repo (this repo, with tfvars files)
      - name: Checkout github user repo
        uses: actions/checkout@v4
        with:
          path: user_repo

      # Checkout the terraform_proxmox repo
      - name: Checkout terraform_proxmox repo
        uses: actions/checkout@v4
        with:
          repository: martyu21/terraform_proxmox
          path: proxmox

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # Initialize Terraform
      - name: Terraform Init
        working-directory: proxmox/proxmox
        run: terraform init

      # Terraform apply for each tfvars file in user repo
      - name: Apply all tfvars
        run: |
          shopt -s nullglob
          for file in user_repo/org/spoke/*/*.tfvars; do
            abs_file="$(realpath "$file")"
            echo "Applying $abs_file..."
            terraform -chdir=proxmox/proxmox apply -auto-approve -var-file="$abs_file"
          done
