name: Deploy Proxmox VMs

on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: self-hosted
    env:
      TF_VAR_access_key: ${{ secrets.ACCESS_KEY }}
      TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

    steps:
      # Checkout the github user repo (this repo, with tfvars files)
      - name: Checkout github user repo
        uses: actions/checkout@v4
        with:
          path: user_repo

      # Checkout the terraform_proxmox repo
      - name: Checkout terraform_proxmox repo
        uses: actions/checkout@v4
        with:
          repository: martyu21/terraform_proxmox
          path: proxmox

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # Initialize Terraform
      - name: Terraform Init
        working-directory: proxmox/proxmox
        run: terraform init


      # Terraform apply for each tfvars file in user repo

      - name: Find changed spokes
        id: changes
        run: |
          changed_spokes=$(git diff --name-only ${{ github.sha }} ${{ github.event.before }} \
            | grep 'user_repo/org/spoke/.*/.*\.tfvars' \
            | xargs -n1 dirname \
            | xargs -n1 basename \
            | sort -u)
          echo "changed_spokes=$changed_spokes" >> $GITHUB_OUTPUT

      # Terraform apply for each tfvars file in user repo

      - name: Apply only changed spokes
        if: steps.changes.outputs.changed_spokes != ''
        run: |
          for spoke in ${{ steps.changes.outputs.changed_spokes }}; do
            echo "Processing spoke $spoke..."
            terraform -chdir=proxmox/proxmox workspace new "$spoke" || true
            terraform -chdir=proxmox/proxmox workspace select "$spoke"
            for file in user_repo/org/spoke/$spoke/*.tfvars; do
              terraform -chdir=proxmox/proxmox apply -auto-approve -var-file="$file"
            done
          done